---
deploy_repository: https://github.com/Dmitriy-O/django-sample-app.git
deploy_branch: main
deploy_user: djangoapp
deploy_app_dir: /opt/django-sample-app
deploy_venv_dir: /opt/django-venv
deploy_env_dir: /etc/django-sample-app
deploy_env_file: /etc/django-sample-app/app.env
deploy_service: django-sample-app
deploy_python: /usr/bin/python3.12
deploy_gunicorn_version: "26.1.0"
deploy_gunicorn_workers: 2
deploy_gunicorn_port: 8000
